### ISSUE TITLE
humanoid robot fall recovery

### ISSUE THREAD

**Issue by Guanbin-Huang** [gaiyi7788/awesome-legged-locomotion-learning#2]
Hi, thank you for your contribution on awesome list related to legged locomotion learning.
I was wondering have you research any related to humanoid robot fall recovery?

**Comment by gaiyi7788** [comment]
Hello, thank you for your interest. I'm sorry that I don't know much about this area.

**Comment by Guanbin-Huang** [comment]
This is what i got so far.
[Learning Complex Motor Skills for Legged RobotFall Recovery](chrome-extension://mhnlakgilnojmhinhkckjpncpbhabphi/pages/pdf/web/viewer.html?file=https%3A%2F%2Fdiscovery.ucl.ac.uk%2Fid%2Feprint%2F10175510%2F1%2FZhibin_Learning_Complex_Motor_Skills_for_Legged_Robot_Fall_Recovery_RAL_Revision.pdf)

and i read it. In the terms of humanoid robot, we only have a related paper but it doesn't talk about falling recovery. And what's more, it just uses a simulated character, it doesn't use the robot. I'm not sure whether the joint and link of robot were considered or not. 

[ASE: large-scale reusable adversarial skill embeddings for physically simulated characters](https://dl.acm.org/doi/abs/10.1145/3528223.3530110) by Jason Peng

**Comment by gaiyi7788** [comment]
I've read this paper as well. This work uses urdf or mjcf models for the simulation, which takes into account the joint and link of robot

**Comment by stephane-caron** [comment]
On a related note, here are two works on fall recovery with a real (adult-size, 40+ kg) humanoid robot:

- **Pre-impact posture shaping:** [Falls control using posture reshaping and active compliance](https://www.researchgate.net/profile/Vincent-Samy/publication/308835404_Falls_control_using_posture_reshaping_and_active_compliance/links/58eb86db0f7e9b6b274b8679/Falls-control-using-posture-reshaping-and-active-compliance.pdf)
- **Post-impact compliance control:** [Post-Impact Adaptive Compliance for Humanoid Falls Using Predictive Control of a Reduced Model](https://hal.science/hal-01569819v2/preview/paperR1%20%281%29.pdf)

<img src="https://github.com/gaiyi7788/awesome-legged-locomotion-learning/assets/1189580/bb917714-2f62-4827-b249-337ef3013d0f" height=150>
